name: AutoTest

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Nightly tests run on master by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ] #macOS-latest, windows-latest

        python-version: [ 3.7 ]

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive


    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file:  devtools/conda-envs/test_env.yaml
        channels: conda-forge,defaults

        activate-environment: restraintmakerTest
        auto-update-conda: true
        auto-activate-base: false
        show-channel-urls: true

    - name: Test with pytest
      run: |
        conda install pytest
        pytest -v --color=yes restraintmaker/test

    #- name: Lint with flake8
    #  run: |
    #    conda install flake8
    #    # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
